/*
Conductor API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conductor

import (
	"encoding/json"
	"fmt"
)

// checks if the QbdInventorySite type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QbdInventorySite{}

// QbdInventorySite struct for QbdInventorySite
type QbdInventorySite struct {
	// The unique identifier assigned by QuickBooks to this inventory site. This ID is unique across all inventory sites but not across different QuickBooks object types.
	Id string `json:"id"`
	// The type of object. This value is always `\"qbd_inventory_site\"`.
	ObjectType string `json:"objectType"`
	// The date and time when this inventory site was created, in ISO 8601 format (YYYY-MM-DDThh:mm:ss±hh:mm). The time zone is the same as the user's time zone in QuickBooks.
	CreatedAt string `json:"createdAt"`
	// The date and time when this inventory site was last updated, in ISO 8601 format (YYYY-MM-DDThh:mm:ss±hh:mm). The time zone is the same as the user's time zone in QuickBooks.
	UpdatedAt string `json:"updatedAt"`
	// The current QuickBooks-assigned revision number of this inventory site object, which changes each time the object is modified. When updating this object, you must provide the most recent `revisionNumber` to ensure you're working with the latest data; otherwise, the update will return an error.
	RevisionNumber string `json:"revisionNumber"`
	// The case-insensitive unique name of this inventory site, unique across all inventory sites.  **NOTE**: Inventory sites do not have a `fullName` field because they are not hierarchical objects, which is why `name` is unique for them but not for objects that have parents.
	Name string `json:"name"`
	// Indicates whether this inventory site is active. Inactive objects are typically hidden from views and reports in QuickBooks. Defaults to `true`.
	IsActive bool `json:"isActive"`
	Parent QbdInventorySiteParent `json:"parent"`
	// Indicates whether this inventory site is the default site used when no specific site is provided during the creation of other objects.
	IsDefault bool `json:"isDefault"`
	// A description of this inventory site.
	Description string `json:"description"`
	// The name of the primary contact person for this inventory site.
	Contact string `json:"contact"`
	// The inventory site's primary telephone number.
	Phone string `json:"phone"`
	// The inventory site's fax number.
	Fax string `json:"fax"`
	// The inventory site's email address.
	Email string `json:"email"`
	Address QbdInventorySiteAddress `json:"address"`
	AdditionalProperties map[string]interface{}
}

type _QbdInventorySite QbdInventorySite

// NewQbdInventorySite instantiates a new QbdInventorySite object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQbdInventorySite(id string, objectType string, createdAt string, updatedAt string, revisionNumber string, name string, isActive bool, parent QbdInventorySiteParent, isDefault bool, description string, contact string, phone string, fax string, email string, address QbdInventorySiteAddress) *QbdInventorySite {
	this := QbdInventorySite{}
	this.Id = id
	this.ObjectType = objectType
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.RevisionNumber = revisionNumber
	this.Name = name
	this.IsActive = isActive
	this.Parent = parent
	this.IsDefault = isDefault
	this.Description = description
	this.Contact = contact
	this.Phone = phone
	this.Fax = fax
	this.Email = email
	this.Address = address
	return &this
}

// NewQbdInventorySiteWithDefaults instantiates a new QbdInventorySite object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQbdInventorySiteWithDefaults() *QbdInventorySite {
	this := QbdInventorySite{}
	return &this
}

// GetId returns the Id field value
func (o *QbdInventorySite) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *QbdInventorySite) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *QbdInventorySite) SetId(v string) {
	o.Id = v
}

// GetObjectType returns the ObjectType field value
func (o *QbdInventorySite) GetObjectType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value
// and a boolean to check if the value has been set.
func (o *QbdInventorySite) GetObjectTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectType, true
}

// SetObjectType sets field value
func (o *QbdInventorySite) SetObjectType(v string) {
	o.ObjectType = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *QbdInventorySite) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *QbdInventorySite) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *QbdInventorySite) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *QbdInventorySite) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *QbdInventorySite) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *QbdInventorySite) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetRevisionNumber returns the RevisionNumber field value
func (o *QbdInventorySite) GetRevisionNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RevisionNumber
}

// GetRevisionNumberOk returns a tuple with the RevisionNumber field value
// and a boolean to check if the value has been set.
func (o *QbdInventorySite) GetRevisionNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RevisionNumber, true
}

// SetRevisionNumber sets field value
func (o *QbdInventorySite) SetRevisionNumber(v string) {
	o.RevisionNumber = v
}

// GetName returns the Name field value
func (o *QbdInventorySite) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *QbdInventorySite) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *QbdInventorySite) SetName(v string) {
	o.Name = v
}

// GetIsActive returns the IsActive field value
func (o *QbdInventorySite) GetIsActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value
// and a boolean to check if the value has been set.
func (o *QbdInventorySite) GetIsActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsActive, true
}

// SetIsActive sets field value
func (o *QbdInventorySite) SetIsActive(v bool) {
	o.IsActive = v
}

// GetParent returns the Parent field value
func (o *QbdInventorySite) GetParent() QbdInventorySiteParent {
	if o == nil {
		var ret QbdInventorySiteParent
		return ret
	}

	return o.Parent
}

// GetParentOk returns a tuple with the Parent field value
// and a boolean to check if the value has been set.
func (o *QbdInventorySite) GetParentOk() (*QbdInventorySiteParent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Parent, true
}

// SetParent sets field value
func (o *QbdInventorySite) SetParent(v QbdInventorySiteParent) {
	o.Parent = v
}

// GetIsDefault returns the IsDefault field value
func (o *QbdInventorySite) GetIsDefault() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsDefault
}

// GetIsDefaultOk returns a tuple with the IsDefault field value
// and a boolean to check if the value has been set.
func (o *QbdInventorySite) GetIsDefaultOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsDefault, true
}

// SetIsDefault sets field value
func (o *QbdInventorySite) SetIsDefault(v bool) {
	o.IsDefault = v
}

// GetDescription returns the Description field value
func (o *QbdInventorySite) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *QbdInventorySite) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *QbdInventorySite) SetDescription(v string) {
	o.Description = v
}

// GetContact returns the Contact field value
func (o *QbdInventorySite) GetContact() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Contact
}

// GetContactOk returns a tuple with the Contact field value
// and a boolean to check if the value has been set.
func (o *QbdInventorySite) GetContactOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Contact, true
}

// SetContact sets field value
func (o *QbdInventorySite) SetContact(v string) {
	o.Contact = v
}

// GetPhone returns the Phone field value
func (o *QbdInventorySite) GetPhone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value
// and a boolean to check if the value has been set.
func (o *QbdInventorySite) GetPhoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phone, true
}

// SetPhone sets field value
func (o *QbdInventorySite) SetPhone(v string) {
	o.Phone = v
}

// GetFax returns the Fax field value
func (o *QbdInventorySite) GetFax() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Fax
}

// GetFaxOk returns a tuple with the Fax field value
// and a boolean to check if the value has been set.
func (o *QbdInventorySite) GetFaxOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fax, true
}

// SetFax sets field value
func (o *QbdInventorySite) SetFax(v string) {
	o.Fax = v
}

// GetEmail returns the Email field value
func (o *QbdInventorySite) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *QbdInventorySite) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *QbdInventorySite) SetEmail(v string) {
	o.Email = v
}

// GetAddress returns the Address field value
func (o *QbdInventorySite) GetAddress() QbdInventorySiteAddress {
	if o == nil {
		var ret QbdInventorySiteAddress
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *QbdInventorySite) GetAddressOk() (*QbdInventorySiteAddress, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *QbdInventorySite) SetAddress(v QbdInventorySiteAddress) {
	o.Address = v
}

func (o QbdInventorySite) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QbdInventorySite) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["objectType"] = o.ObjectType
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	toSerialize["revisionNumber"] = o.RevisionNumber
	toSerialize["name"] = o.Name
	toSerialize["isActive"] = o.IsActive
	toSerialize["parent"] = o.Parent
	toSerialize["isDefault"] = o.IsDefault
	toSerialize["description"] = o.Description
	toSerialize["contact"] = o.Contact
	toSerialize["phone"] = o.Phone
	toSerialize["fax"] = o.Fax
	toSerialize["email"] = o.Email
	toSerialize["address"] = o.Address

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *QbdInventorySite) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"objectType",
		"createdAt",
		"updatedAt",
		"revisionNumber",
		"name",
		"isActive",
		"parent",
		"isDefault",
		"description",
		"contact",
		"phone",
		"fax",
		"email",
		"address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQbdInventorySite := _QbdInventorySite{}

	err = json.Unmarshal(data, &varQbdInventorySite)

	if err != nil {
		return err
	}

	*o = QbdInventorySite(varQbdInventorySite)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "objectType")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		delete(additionalProperties, "revisionNumber")
		delete(additionalProperties, "name")
		delete(additionalProperties, "isActive")
		delete(additionalProperties, "parent")
		delete(additionalProperties, "isDefault")
		delete(additionalProperties, "description")
		delete(additionalProperties, "contact")
		delete(additionalProperties, "phone")
		delete(additionalProperties, "fax")
		delete(additionalProperties, "email")
		delete(additionalProperties, "address")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableQbdInventorySite struct {
	value *QbdInventorySite
	isSet bool
}

func (v NullableQbdInventorySite) Get() *QbdInventorySite {
	return v.value
}

func (v *NullableQbdInventorySite) Set(val *QbdInventorySite) {
	v.value = val
	v.isSet = true
}

func (v NullableQbdInventorySite) IsSet() bool {
	return v.isSet
}

func (v *NullableQbdInventorySite) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQbdInventorySite(val *QbdInventorySite) *NullableQbdInventorySite {
	return &NullableQbdInventorySite{value: val, isSet: true}
}

func (v NullableQbdInventorySite) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQbdInventorySite) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


