/*
Conductor API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conductor

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QbdInvoiceReceivablesAccount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QbdInvoiceReceivablesAccount{}

// QbdInvoiceReceivablesAccount The Accounts-Receivable (A/R) account to which this invoice is assigned, used to track the amount owed. If not specified, QuickBooks Desktop will use its default A/R account.  **IMPORTANT**: If this invoice is linked to other transactions, this A/R account must match the `receivablesAccount` used in all linked transactions. For example, when refunding a credit card payment, the A/R account must match the one used in the original credit transactions being refunded.
type QbdInvoiceReceivablesAccount struct {
	// The unique identifier assigned by QuickBooks to this object. This ID is unique across all objects of the same type, but not across different QuickBooks object types.
	Id string `json:"id"`
	// The fully-qualified unique name for this object, formed by combining the names of its parent objects with its own `name`, separated by colons. Not case-sensitive.
	FullName string `json:"fullName"`
}

type _QbdInvoiceReceivablesAccount QbdInvoiceReceivablesAccount

// NewQbdInvoiceReceivablesAccount instantiates a new QbdInvoiceReceivablesAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQbdInvoiceReceivablesAccount(id string, fullName string) *QbdInvoiceReceivablesAccount {
	this := QbdInvoiceReceivablesAccount{}
	this.Id = id
	this.FullName = fullName
	return &this
}

// NewQbdInvoiceReceivablesAccountWithDefaults instantiates a new QbdInvoiceReceivablesAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQbdInvoiceReceivablesAccountWithDefaults() *QbdInvoiceReceivablesAccount {
	this := QbdInvoiceReceivablesAccount{}
	return &this
}

// GetId returns the Id field value
func (o *QbdInvoiceReceivablesAccount) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *QbdInvoiceReceivablesAccount) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *QbdInvoiceReceivablesAccount) SetId(v string) {
	o.Id = v
}

// GetFullName returns the FullName field value
func (o *QbdInvoiceReceivablesAccount) GetFullName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FullName
}

// GetFullNameOk returns a tuple with the FullName field value
// and a boolean to check if the value has been set.
func (o *QbdInvoiceReceivablesAccount) GetFullNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FullName, true
}

// SetFullName sets field value
func (o *QbdInvoiceReceivablesAccount) SetFullName(v string) {
	o.FullName = v
}

func (o QbdInvoiceReceivablesAccount) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QbdInvoiceReceivablesAccount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["fullName"] = o.FullName
	return toSerialize, nil
}

func (o *QbdInvoiceReceivablesAccount) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"fullName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQbdInvoiceReceivablesAccount := _QbdInvoiceReceivablesAccount{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQbdInvoiceReceivablesAccount)

	if err != nil {
		return err
	}

	*o = QbdInvoiceReceivablesAccount(varQbdInvoiceReceivablesAccount)

	return err
}

type NullableQbdInvoiceReceivablesAccount struct {
	value *QbdInvoiceReceivablesAccount
	isSet bool
}

func (v NullableQbdInvoiceReceivablesAccount) Get() *QbdInvoiceReceivablesAccount {
	return v.value
}

func (v *NullableQbdInvoiceReceivablesAccount) Set(val *QbdInvoiceReceivablesAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableQbdInvoiceReceivablesAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableQbdInvoiceReceivablesAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQbdInvoiceReceivablesAccount(val *QbdInvoiceReceivablesAccount) *NullableQbdInvoiceReceivablesAccount {
	return &NullableQbdInvoiceReceivablesAccount{value: val, isSet: true}
}

func (v NullableQbdInvoiceReceivablesAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQbdInvoiceReceivablesAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


