/*
Conductor API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conductor

import (
	"encoding/json"
	"fmt"
)

// checks if the QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner{}

// QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner struct for QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner
type QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner struct {
	// The case-insensitive unique name of this shipping address, unique across all shipping addresses.  **NOTE**: Shipping addresses do not have a `fullName` field because they are not hierarchical objects, which is why `name` is unique for them but not for objects that have parents.  Maximum length: 41 characters.
	Name string `json:"name"`
	// The first line of the shipping address (e.g., street, PO Box, or company name).  Maximum length: 41 characters.
	Line1 *string `json:"line1,omitempty"`
	// The second line of the shipping address, if needed (e.g., apartment, suite, unit, or building).  Maximum length: 41 characters.
	Line2 *string `json:"line2,omitempty"`
	// The third line of the shipping address, if needed.  Maximum length: 41 characters.
	Line3 *string `json:"line3,omitempty"`
	// The fourth line of the shipping address, if needed.  Maximum length: 41 characters.
	Line4 *string `json:"line4,omitempty"`
	// The fifth line of the shipping address, if needed.  Maximum length: 41 characters.
	Line5 *string `json:"line5,omitempty"`
	// The city, district, suburb, town, or village name of the shipping address.  Maximum length: 31 characters.
	City *string `json:"city,omitempty"`
	// The state, county, province, or region name of the shipping address.  Maximum length: 21 characters.
	State *string `json:"state,omitempty"`
	// The postal code or ZIP code of the shipping address.  Maximum length: 13 characters.
	PostalCode *string `json:"postalCode,omitempty"`
	// The country name of the shipping address.
	Country *string `json:"country,omitempty"`
	// A note written at the bottom of the shipping address in the form in which it appears, such as the invoice form.
	Note *string `json:"note,omitempty"`
	// Indicates whether this shipping address is the default shipping address.
	IsDefaultShippingAddress *bool `json:"isDefaultShippingAddress,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner

// NewQuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner instantiates a new QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner(name string) *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner {
	this := QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner{}
	this.Name = name
	return &this
}

// NewQuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInnerWithDefaults instantiates a new QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInnerWithDefaults() *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner {
	this := QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner{}
	return &this
}

// GetName returns the Name field value
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) SetName(v string) {
	o.Name = v
}

// GetLine1 returns the Line1 field value if set, zero value otherwise.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) GetLine1() string {
	if o == nil || IsNil(o.Line1) {
		var ret string
		return ret
	}
	return *o.Line1
}

// GetLine1Ok returns a tuple with the Line1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) GetLine1Ok() (*string, bool) {
	if o == nil || IsNil(o.Line1) {
		return nil, false
	}
	return o.Line1, true
}

// HasLine1 returns a boolean if a field has been set.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) HasLine1() bool {
	if o != nil && !IsNil(o.Line1) {
		return true
	}

	return false
}

// SetLine1 gets a reference to the given string and assigns it to the Line1 field.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) SetLine1(v string) {
	o.Line1 = &v
}

// GetLine2 returns the Line2 field value if set, zero value otherwise.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) GetLine2() string {
	if o == nil || IsNil(o.Line2) {
		var ret string
		return ret
	}
	return *o.Line2
}

// GetLine2Ok returns a tuple with the Line2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) GetLine2Ok() (*string, bool) {
	if o == nil || IsNil(o.Line2) {
		return nil, false
	}
	return o.Line2, true
}

// HasLine2 returns a boolean if a field has been set.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) HasLine2() bool {
	if o != nil && !IsNil(o.Line2) {
		return true
	}

	return false
}

// SetLine2 gets a reference to the given string and assigns it to the Line2 field.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) SetLine2(v string) {
	o.Line2 = &v
}

// GetLine3 returns the Line3 field value if set, zero value otherwise.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) GetLine3() string {
	if o == nil || IsNil(o.Line3) {
		var ret string
		return ret
	}
	return *o.Line3
}

// GetLine3Ok returns a tuple with the Line3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) GetLine3Ok() (*string, bool) {
	if o == nil || IsNil(o.Line3) {
		return nil, false
	}
	return o.Line3, true
}

// HasLine3 returns a boolean if a field has been set.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) HasLine3() bool {
	if o != nil && !IsNil(o.Line3) {
		return true
	}

	return false
}

// SetLine3 gets a reference to the given string and assigns it to the Line3 field.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) SetLine3(v string) {
	o.Line3 = &v
}

// GetLine4 returns the Line4 field value if set, zero value otherwise.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) GetLine4() string {
	if o == nil || IsNil(o.Line4) {
		var ret string
		return ret
	}
	return *o.Line4
}

// GetLine4Ok returns a tuple with the Line4 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) GetLine4Ok() (*string, bool) {
	if o == nil || IsNil(o.Line4) {
		return nil, false
	}
	return o.Line4, true
}

// HasLine4 returns a boolean if a field has been set.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) HasLine4() bool {
	if o != nil && !IsNil(o.Line4) {
		return true
	}

	return false
}

// SetLine4 gets a reference to the given string and assigns it to the Line4 field.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) SetLine4(v string) {
	o.Line4 = &v
}

// GetLine5 returns the Line5 field value if set, zero value otherwise.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) GetLine5() string {
	if o == nil || IsNil(o.Line5) {
		var ret string
		return ret
	}
	return *o.Line5
}

// GetLine5Ok returns a tuple with the Line5 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) GetLine5Ok() (*string, bool) {
	if o == nil || IsNil(o.Line5) {
		return nil, false
	}
	return o.Line5, true
}

// HasLine5 returns a boolean if a field has been set.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) HasLine5() bool {
	if o != nil && !IsNil(o.Line5) {
		return true
	}

	return false
}

// SetLine5 gets a reference to the given string and assigns it to the Line5 field.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) SetLine5(v string) {
	o.Line5 = &v
}

// GetCity returns the City field value if set, zero value otherwise.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) GetCity() string {
	if o == nil || IsNil(o.City) {
		var ret string
		return ret
	}
	return *o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) GetCityOk() (*string, bool) {
	if o == nil || IsNil(o.City) {
		return nil, false
	}
	return o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) HasCity() bool {
	if o != nil && !IsNil(o.City) {
		return true
	}

	return false
}

// SetCity gets a reference to the given string and assigns it to the City field.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) SetCity(v string) {
	o.City = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) SetState(v string) {
	o.State = &v
}

// GetPostalCode returns the PostalCode field value if set, zero value otherwise.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) GetPostalCode() string {
	if o == nil || IsNil(o.PostalCode) {
		var ret string
		return ret
	}
	return *o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) GetPostalCodeOk() (*string, bool) {
	if o == nil || IsNil(o.PostalCode) {
		return nil, false
	}
	return o.PostalCode, true
}

// HasPostalCode returns a boolean if a field has been set.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) HasPostalCode() bool {
	if o != nil && !IsNil(o.PostalCode) {
		return true
	}

	return false
}

// SetPostalCode gets a reference to the given string and assigns it to the PostalCode field.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) SetPostalCode(v string) {
	o.PostalCode = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) SetCountry(v string) {
	o.Country = &v
}

// GetNote returns the Note field value if set, zero value otherwise.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) GetNote() string {
	if o == nil || IsNil(o.Note) {
		var ret string
		return ret
	}
	return *o.Note
}

// GetNoteOk returns a tuple with the Note field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) GetNoteOk() (*string, bool) {
	if o == nil || IsNil(o.Note) {
		return nil, false
	}
	return o.Note, true
}

// HasNote returns a boolean if a field has been set.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) HasNote() bool {
	if o != nil && !IsNil(o.Note) {
		return true
	}

	return false
}

// SetNote gets a reference to the given string and assigns it to the Note field.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) SetNote(v string) {
	o.Note = &v
}

// GetIsDefaultShippingAddress returns the IsDefaultShippingAddress field value if set, zero value otherwise.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) GetIsDefaultShippingAddress() bool {
	if o == nil || IsNil(o.IsDefaultShippingAddress) {
		var ret bool
		return ret
	}
	return *o.IsDefaultShippingAddress
}

// GetIsDefaultShippingAddressOk returns a tuple with the IsDefaultShippingAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) GetIsDefaultShippingAddressOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDefaultShippingAddress) {
		return nil, false
	}
	return o.IsDefaultShippingAddress, true
}

// HasIsDefaultShippingAddress returns a boolean if a field has been set.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) HasIsDefaultShippingAddress() bool {
	if o != nil && !IsNil(o.IsDefaultShippingAddress) {
		return true
	}

	return false
}

// SetIsDefaultShippingAddress gets a reference to the given bool and assigns it to the IsDefaultShippingAddress field.
func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) SetIsDefaultShippingAddress(v bool) {
	o.IsDefaultShippingAddress = &v
}

func (o QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Line1) {
		toSerialize["line1"] = o.Line1
	}
	if !IsNil(o.Line2) {
		toSerialize["line2"] = o.Line2
	}
	if !IsNil(o.Line3) {
		toSerialize["line3"] = o.Line3
	}
	if !IsNil(o.Line4) {
		toSerialize["line4"] = o.Line4
	}
	if !IsNil(o.Line5) {
		toSerialize["line5"] = o.Line5
	}
	if !IsNil(o.City) {
		toSerialize["city"] = o.City
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.PostalCode) {
		toSerialize["postalCode"] = o.PostalCode
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.Note) {
		toSerialize["note"] = o.Note
	}
	if !IsNil(o.IsDefaultShippingAddress) {
		toSerialize["isDefaultShippingAddress"] = o.IsDefaultShippingAddress
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner := _QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner{}

	err = json.Unmarshal(data, &varQuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner)

	if err != nil {
		return err
	}

	*o = QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner(varQuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "line1")
		delete(additionalProperties, "line2")
		delete(additionalProperties, "line3")
		delete(additionalProperties, "line4")
		delete(additionalProperties, "line5")
		delete(additionalProperties, "city")
		delete(additionalProperties, "state")
		delete(additionalProperties, "postalCode")
		delete(additionalProperties, "country")
		delete(additionalProperties, "note")
		delete(additionalProperties, "isDefaultShippingAddress")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableQuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner struct {
	value *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner
	isSet bool
}

func (v NullableQuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) Get() *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner {
	return v.value
}

func (v *NullableQuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) Set(val *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableQuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableQuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner(val *QuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) *NullableQuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner {
	return &NullableQuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner{value: val, isSet: true}
}

func (v NullableQuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuickbooksDesktopCustomersPostRequestAlternateShippingAddressesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


