/*
Conductor API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conductor

import (
	"encoding/json"
	"fmt"
)

// checks if the QuickbooksDesktopTransfersPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuickbooksDesktopTransfersPostRequest{}

// QuickbooksDesktopTransfersPostRequest struct for QuickbooksDesktopTransfersPostRequest
type QuickbooksDesktopTransfersPostRequest struct {
	// The date of this transfer, in ISO 8601 format (YYYY-MM-DD).
	TransactionDate string `json:"transactionDate"`
	// The account from which money will be transferred.
	SourceAccountId string `json:"sourceAccountId"`
	// The account to which money will be transferred.
	TargetAccountId string `json:"targetAccountId"`
	// The transfer's class. Classes can be used to categorize objects into meaningful segments, such as department, location, or type of work. In QuickBooks, class tracking is off by default.
	ClassId *string `json:"classId,omitempty"`
	// The monetary amount of this transfer, represented as a decimal string.
	Amount string `json:"amount"`
	// A memo or note for this transfer.
	Memo *string `json:"memo,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _QuickbooksDesktopTransfersPostRequest QuickbooksDesktopTransfersPostRequest

// NewQuickbooksDesktopTransfersPostRequest instantiates a new QuickbooksDesktopTransfersPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuickbooksDesktopTransfersPostRequest(transactionDate string, sourceAccountId string, targetAccountId string, amount string) *QuickbooksDesktopTransfersPostRequest {
	this := QuickbooksDesktopTransfersPostRequest{}
	this.TransactionDate = transactionDate
	this.SourceAccountId = sourceAccountId
	this.TargetAccountId = targetAccountId
	this.Amount = amount
	return &this
}

// NewQuickbooksDesktopTransfersPostRequestWithDefaults instantiates a new QuickbooksDesktopTransfersPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuickbooksDesktopTransfersPostRequestWithDefaults() *QuickbooksDesktopTransfersPostRequest {
	this := QuickbooksDesktopTransfersPostRequest{}
	return &this
}

// GetTransactionDate returns the TransactionDate field value
func (o *QuickbooksDesktopTransfersPostRequest) GetTransactionDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionDate
}

// GetTransactionDateOk returns a tuple with the TransactionDate field value
// and a boolean to check if the value has been set.
func (o *QuickbooksDesktopTransfersPostRequest) GetTransactionDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionDate, true
}

// SetTransactionDate sets field value
func (o *QuickbooksDesktopTransfersPostRequest) SetTransactionDate(v string) {
	o.TransactionDate = v
}

// GetSourceAccountId returns the SourceAccountId field value
func (o *QuickbooksDesktopTransfersPostRequest) GetSourceAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceAccountId
}

// GetSourceAccountIdOk returns a tuple with the SourceAccountId field value
// and a boolean to check if the value has been set.
func (o *QuickbooksDesktopTransfersPostRequest) GetSourceAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceAccountId, true
}

// SetSourceAccountId sets field value
func (o *QuickbooksDesktopTransfersPostRequest) SetSourceAccountId(v string) {
	o.SourceAccountId = v
}

// GetTargetAccountId returns the TargetAccountId field value
func (o *QuickbooksDesktopTransfersPostRequest) GetTargetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetAccountId
}

// GetTargetAccountIdOk returns a tuple with the TargetAccountId field value
// and a boolean to check if the value has been set.
func (o *QuickbooksDesktopTransfersPostRequest) GetTargetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetAccountId, true
}

// SetTargetAccountId sets field value
func (o *QuickbooksDesktopTransfersPostRequest) SetTargetAccountId(v string) {
	o.TargetAccountId = v
}

// GetClassId returns the ClassId field value if set, zero value otherwise.
func (o *QuickbooksDesktopTransfersPostRequest) GetClassId() string {
	if o == nil || IsNil(o.ClassId) {
		var ret string
		return ret
	}
	return *o.ClassId
}

// GetClassIdOk returns a tuple with the ClassId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuickbooksDesktopTransfersPostRequest) GetClassIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClassId) {
		return nil, false
	}
	return o.ClassId, true
}

// HasClassId returns a boolean if a field has been set.
func (o *QuickbooksDesktopTransfersPostRequest) HasClassId() bool {
	if o != nil && !IsNil(o.ClassId) {
		return true
	}

	return false
}

// SetClassId gets a reference to the given string and assigns it to the ClassId field.
func (o *QuickbooksDesktopTransfersPostRequest) SetClassId(v string) {
	o.ClassId = &v
}

// GetAmount returns the Amount field value
func (o *QuickbooksDesktopTransfersPostRequest) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *QuickbooksDesktopTransfersPostRequest) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *QuickbooksDesktopTransfersPostRequest) SetAmount(v string) {
	o.Amount = v
}

// GetMemo returns the Memo field value if set, zero value otherwise.
func (o *QuickbooksDesktopTransfersPostRequest) GetMemo() string {
	if o == nil || IsNil(o.Memo) {
		var ret string
		return ret
	}
	return *o.Memo
}

// GetMemoOk returns a tuple with the Memo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuickbooksDesktopTransfersPostRequest) GetMemoOk() (*string, bool) {
	if o == nil || IsNil(o.Memo) {
		return nil, false
	}
	return o.Memo, true
}

// HasMemo returns a boolean if a field has been set.
func (o *QuickbooksDesktopTransfersPostRequest) HasMemo() bool {
	if o != nil && !IsNil(o.Memo) {
		return true
	}

	return false
}

// SetMemo gets a reference to the given string and assigns it to the Memo field.
func (o *QuickbooksDesktopTransfersPostRequest) SetMemo(v string) {
	o.Memo = &v
}

func (o QuickbooksDesktopTransfersPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuickbooksDesktopTransfersPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["transactionDate"] = o.TransactionDate
	toSerialize["sourceAccountId"] = o.SourceAccountId
	toSerialize["targetAccountId"] = o.TargetAccountId
	if !IsNil(o.ClassId) {
		toSerialize["classId"] = o.ClassId
	}
	toSerialize["amount"] = o.Amount
	if !IsNil(o.Memo) {
		toSerialize["memo"] = o.Memo
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *QuickbooksDesktopTransfersPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"transactionDate",
		"sourceAccountId",
		"targetAccountId",
		"amount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQuickbooksDesktopTransfersPostRequest := _QuickbooksDesktopTransfersPostRequest{}

	err = json.Unmarshal(data, &varQuickbooksDesktopTransfersPostRequest)

	if err != nil {
		return err
	}

	*o = QuickbooksDesktopTransfersPostRequest(varQuickbooksDesktopTransfersPostRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "transactionDate")
		delete(additionalProperties, "sourceAccountId")
		delete(additionalProperties, "targetAccountId")
		delete(additionalProperties, "classId")
		delete(additionalProperties, "amount")
		delete(additionalProperties, "memo")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableQuickbooksDesktopTransfersPostRequest struct {
	value *QuickbooksDesktopTransfersPostRequest
	isSet bool
}

func (v NullableQuickbooksDesktopTransfersPostRequest) Get() *QuickbooksDesktopTransfersPostRequest {
	return v.value
}

func (v *NullableQuickbooksDesktopTransfersPostRequest) Set(val *QuickbooksDesktopTransfersPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableQuickbooksDesktopTransfersPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableQuickbooksDesktopTransfersPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuickbooksDesktopTransfersPostRequest(val *QuickbooksDesktopTransfersPostRequest) *NullableQuickbooksDesktopTransfersPostRequest {
	return &NullableQuickbooksDesktopTransfersPostRequest{value: val, isSet: true}
}

func (v NullableQuickbooksDesktopTransfersPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuickbooksDesktopTransfersPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


