/*
Conductor API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conductor

import (
	"encoding/json"
	"fmt"
)

// checks if the QbdDiscountItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QbdDiscountItem{}

// QbdDiscountItem struct for QbdDiscountItem
type QbdDiscountItem struct {
	// The unique identifier assigned by QuickBooks to this discount item. This ID is unique across all discount items but not across different QuickBooks object types.
	Id string `json:"id"`
	// The type of object. This value is always `\"qbd_discount_item\"`.
	ObjectType string `json:"objectType"`
	// The date and time when this discount item was created, in ISO 8601 format (YYYY-MM-DDThh:mm:ss±hh:mm). The time zone is the same as the user's time zone in QuickBooks.
	CreatedAt string `json:"createdAt"`
	// The date and time when this discount item was last updated, in ISO 8601 format (YYYY-MM-DDThh:mm:ss±hh:mm). The time zone is the same as the user's time zone in QuickBooks.
	UpdatedAt string `json:"updatedAt"`
	// The current QuickBooks-assigned revision number of this discount item object, which changes each time the object is modified. When updating this object, you must provide the most recent `revisionNumber` to ensure you're working with the latest data; otherwise, the update will return an error.
	RevisionNumber string `json:"revisionNumber"`
	// The case-insensitive name of this discount item. Not guaranteed to be unique because it does not include the names of its hierarchical parent objects like `fullName` does. For example, two discount items could both have the `name` \"10% labor discount\", but they could have unique `fullName` values, such as \"Discounts:10% labor discount\" and \"Promotions:10% labor discount\".
	Name string `json:"name"`
	// The case-insensitive fully-qualified unique name of this discount item, formed by combining the names of its hierarchical parent objects with its own `name`, separated by colons. For example, if a discount item is under \"Discounts\" and has the `name` \"10% labor discount\", its `fullName` would be \"Discounts:10% labor discount\".  **NOTE**: Unlike `name`, `fullName` is guaranteed to be unique across all discount item objects. However, `fullName` can still be arbitrarily changed by the QuickBooks user when they modify the underlying `name` field.
	FullName string `json:"fullName"`
	// The discount item's barcode.
	Barcode string `json:"barcode"`
	// Indicates whether this discount item is active. Inactive objects are typically hidden from views and reports in QuickBooks. Defaults to `true`.
	IsActive bool `json:"isActive"`
	Class QbdDiscountItemClass `json:"class"`
	Parent QbdDiscountItemParent `json:"parent"`
	// The depth level of this discount item in the hierarchy. A top-level discount item has a `sublevel` of 0; each subsequent sublevel increases this number by 1. For example, a discount item with a `fullName` of \"Discounts:10% labor discount\" would have a `sublevel` of 1.
	Sublevel float32 `json:"sublevel"`
	// The discount item's description that will appear on sales forms that include this item.
	Description string `json:"description"`
	SalesTaxCode QbdDiscountItemSalesTaxCode `json:"salesTaxCode"`
	// The monetary amount to subtract from the total or subtotal when applying this discount item to a transaction.  **NOTE**: A flat rate discount applies to ALL lines recorded above it and distributes the discount amount equally across those lines, which affects tax calculations. For example, a $10 discount applied to a $100 taxable item and $100 non-taxable item would result in a $5 taxable discount and $5 non-taxable discount.
	DiscountRate string `json:"discountRate"`
	// The percentage amount to subtract from the total or subtotal when applying this discount item to a transaction.  **NOTE**: A percentage discount only applies to the line immediately above it, so tax implications only affect that specific line.
	DiscountRatePercent string `json:"discountRatePercent"`
	Account QbdDiscountItemAccount `json:"account"`
	// A globally unique identifier (GUID) you, the developer, can provide for tracking this object in your external system. This field is immutable and can only be set during object creation.
	ExternalId string `json:"externalId"`
	// The custom fields for the discount item object, added as user-defined data extensions, not included in the standard QuickBooks object.
	CustomFields []QbdCustomField `json:"customFields"`
	AdditionalProperties map[string]interface{}
}

type _QbdDiscountItem QbdDiscountItem

// NewQbdDiscountItem instantiates a new QbdDiscountItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQbdDiscountItem(id string, objectType string, createdAt string, updatedAt string, revisionNumber string, name string, fullName string, barcode string, isActive bool, class QbdDiscountItemClass, parent QbdDiscountItemParent, sublevel float32, description string, salesTaxCode QbdDiscountItemSalesTaxCode, discountRate string, discountRatePercent string, account QbdDiscountItemAccount, externalId string, customFields []QbdCustomField) *QbdDiscountItem {
	this := QbdDiscountItem{}
	this.Id = id
	this.ObjectType = objectType
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.RevisionNumber = revisionNumber
	this.Name = name
	this.FullName = fullName
	this.Barcode = barcode
	this.IsActive = isActive
	this.Class = class
	this.Parent = parent
	this.Sublevel = sublevel
	this.Description = description
	this.SalesTaxCode = salesTaxCode
	this.DiscountRate = discountRate
	this.DiscountRatePercent = discountRatePercent
	this.Account = account
	this.ExternalId = externalId
	this.CustomFields = customFields
	return &this
}

// NewQbdDiscountItemWithDefaults instantiates a new QbdDiscountItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQbdDiscountItemWithDefaults() *QbdDiscountItem {
	this := QbdDiscountItem{}
	return &this
}

// GetId returns the Id field value
func (o *QbdDiscountItem) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *QbdDiscountItem) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *QbdDiscountItem) SetId(v string) {
	o.Id = v
}

// GetObjectType returns the ObjectType field value
func (o *QbdDiscountItem) GetObjectType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value
// and a boolean to check if the value has been set.
func (o *QbdDiscountItem) GetObjectTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectType, true
}

// SetObjectType sets field value
func (o *QbdDiscountItem) SetObjectType(v string) {
	o.ObjectType = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *QbdDiscountItem) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *QbdDiscountItem) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *QbdDiscountItem) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *QbdDiscountItem) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *QbdDiscountItem) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *QbdDiscountItem) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetRevisionNumber returns the RevisionNumber field value
func (o *QbdDiscountItem) GetRevisionNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RevisionNumber
}

// GetRevisionNumberOk returns a tuple with the RevisionNumber field value
// and a boolean to check if the value has been set.
func (o *QbdDiscountItem) GetRevisionNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RevisionNumber, true
}

// SetRevisionNumber sets field value
func (o *QbdDiscountItem) SetRevisionNumber(v string) {
	o.RevisionNumber = v
}

// GetName returns the Name field value
func (o *QbdDiscountItem) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *QbdDiscountItem) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *QbdDiscountItem) SetName(v string) {
	o.Name = v
}

// GetFullName returns the FullName field value
func (o *QbdDiscountItem) GetFullName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FullName
}

// GetFullNameOk returns a tuple with the FullName field value
// and a boolean to check if the value has been set.
func (o *QbdDiscountItem) GetFullNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FullName, true
}

// SetFullName sets field value
func (o *QbdDiscountItem) SetFullName(v string) {
	o.FullName = v
}

// GetBarcode returns the Barcode field value
func (o *QbdDiscountItem) GetBarcode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Barcode
}

// GetBarcodeOk returns a tuple with the Barcode field value
// and a boolean to check if the value has been set.
func (o *QbdDiscountItem) GetBarcodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Barcode, true
}

// SetBarcode sets field value
func (o *QbdDiscountItem) SetBarcode(v string) {
	o.Barcode = v
}

// GetIsActive returns the IsActive field value
func (o *QbdDiscountItem) GetIsActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value
// and a boolean to check if the value has been set.
func (o *QbdDiscountItem) GetIsActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsActive, true
}

// SetIsActive sets field value
func (o *QbdDiscountItem) SetIsActive(v bool) {
	o.IsActive = v
}

// GetClass returns the Class field value
func (o *QbdDiscountItem) GetClass() QbdDiscountItemClass {
	if o == nil {
		var ret QbdDiscountItemClass
		return ret
	}

	return o.Class
}

// GetClassOk returns a tuple with the Class field value
// and a boolean to check if the value has been set.
func (o *QbdDiscountItem) GetClassOk() (*QbdDiscountItemClass, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Class, true
}

// SetClass sets field value
func (o *QbdDiscountItem) SetClass(v QbdDiscountItemClass) {
	o.Class = v
}

// GetParent returns the Parent field value
func (o *QbdDiscountItem) GetParent() QbdDiscountItemParent {
	if o == nil {
		var ret QbdDiscountItemParent
		return ret
	}

	return o.Parent
}

// GetParentOk returns a tuple with the Parent field value
// and a boolean to check if the value has been set.
func (o *QbdDiscountItem) GetParentOk() (*QbdDiscountItemParent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Parent, true
}

// SetParent sets field value
func (o *QbdDiscountItem) SetParent(v QbdDiscountItemParent) {
	o.Parent = v
}

// GetSublevel returns the Sublevel field value
func (o *QbdDiscountItem) GetSublevel() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Sublevel
}

// GetSublevelOk returns a tuple with the Sublevel field value
// and a boolean to check if the value has been set.
func (o *QbdDiscountItem) GetSublevelOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sublevel, true
}

// SetSublevel sets field value
func (o *QbdDiscountItem) SetSublevel(v float32) {
	o.Sublevel = v
}

// GetDescription returns the Description field value
func (o *QbdDiscountItem) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *QbdDiscountItem) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *QbdDiscountItem) SetDescription(v string) {
	o.Description = v
}

// GetSalesTaxCode returns the SalesTaxCode field value
func (o *QbdDiscountItem) GetSalesTaxCode() QbdDiscountItemSalesTaxCode {
	if o == nil {
		var ret QbdDiscountItemSalesTaxCode
		return ret
	}

	return o.SalesTaxCode
}

// GetSalesTaxCodeOk returns a tuple with the SalesTaxCode field value
// and a boolean to check if the value has been set.
func (o *QbdDiscountItem) GetSalesTaxCodeOk() (*QbdDiscountItemSalesTaxCode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SalesTaxCode, true
}

// SetSalesTaxCode sets field value
func (o *QbdDiscountItem) SetSalesTaxCode(v QbdDiscountItemSalesTaxCode) {
	o.SalesTaxCode = v
}

// GetDiscountRate returns the DiscountRate field value
func (o *QbdDiscountItem) GetDiscountRate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DiscountRate
}

// GetDiscountRateOk returns a tuple with the DiscountRate field value
// and a boolean to check if the value has been set.
func (o *QbdDiscountItem) GetDiscountRateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DiscountRate, true
}

// SetDiscountRate sets field value
func (o *QbdDiscountItem) SetDiscountRate(v string) {
	o.DiscountRate = v
}

// GetDiscountRatePercent returns the DiscountRatePercent field value
func (o *QbdDiscountItem) GetDiscountRatePercent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DiscountRatePercent
}

// GetDiscountRatePercentOk returns a tuple with the DiscountRatePercent field value
// and a boolean to check if the value has been set.
func (o *QbdDiscountItem) GetDiscountRatePercentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DiscountRatePercent, true
}

// SetDiscountRatePercent sets field value
func (o *QbdDiscountItem) SetDiscountRatePercent(v string) {
	o.DiscountRatePercent = v
}

// GetAccount returns the Account field value
func (o *QbdDiscountItem) GetAccount() QbdDiscountItemAccount {
	if o == nil {
		var ret QbdDiscountItemAccount
		return ret
	}

	return o.Account
}

// GetAccountOk returns a tuple with the Account field value
// and a boolean to check if the value has been set.
func (o *QbdDiscountItem) GetAccountOk() (*QbdDiscountItemAccount, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Account, true
}

// SetAccount sets field value
func (o *QbdDiscountItem) SetAccount(v QbdDiscountItemAccount) {
	o.Account = v
}

// GetExternalId returns the ExternalId field value
func (o *QbdDiscountItem) GetExternalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value
// and a boolean to check if the value has been set.
func (o *QbdDiscountItem) GetExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalId, true
}

// SetExternalId sets field value
func (o *QbdDiscountItem) SetExternalId(v string) {
	o.ExternalId = v
}

// GetCustomFields returns the CustomFields field value
func (o *QbdDiscountItem) GetCustomFields() []QbdCustomField {
	if o == nil {
		var ret []QbdCustomField
		return ret
	}

	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value
// and a boolean to check if the value has been set.
func (o *QbdDiscountItem) GetCustomFieldsOk() ([]QbdCustomField, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomFields, true
}

// SetCustomFields sets field value
func (o *QbdDiscountItem) SetCustomFields(v []QbdCustomField) {
	o.CustomFields = v
}

func (o QbdDiscountItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QbdDiscountItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["objectType"] = o.ObjectType
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	toSerialize["revisionNumber"] = o.RevisionNumber
	toSerialize["name"] = o.Name
	toSerialize["fullName"] = o.FullName
	toSerialize["barcode"] = o.Barcode
	toSerialize["isActive"] = o.IsActive
	toSerialize["class"] = o.Class
	toSerialize["parent"] = o.Parent
	toSerialize["sublevel"] = o.Sublevel
	toSerialize["description"] = o.Description
	toSerialize["salesTaxCode"] = o.SalesTaxCode
	toSerialize["discountRate"] = o.DiscountRate
	toSerialize["discountRatePercent"] = o.DiscountRatePercent
	toSerialize["account"] = o.Account
	toSerialize["externalId"] = o.ExternalId
	toSerialize["customFields"] = o.CustomFields

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *QbdDiscountItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"objectType",
		"createdAt",
		"updatedAt",
		"revisionNumber",
		"name",
		"fullName",
		"barcode",
		"isActive",
		"class",
		"parent",
		"sublevel",
		"description",
		"salesTaxCode",
		"discountRate",
		"discountRatePercent",
		"account",
		"externalId",
		"customFields",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQbdDiscountItem := _QbdDiscountItem{}

	err = json.Unmarshal(data, &varQbdDiscountItem)

	if err != nil {
		return err
	}

	*o = QbdDiscountItem(varQbdDiscountItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "objectType")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		delete(additionalProperties, "revisionNumber")
		delete(additionalProperties, "name")
		delete(additionalProperties, "fullName")
		delete(additionalProperties, "barcode")
		delete(additionalProperties, "isActive")
		delete(additionalProperties, "class")
		delete(additionalProperties, "parent")
		delete(additionalProperties, "sublevel")
		delete(additionalProperties, "description")
		delete(additionalProperties, "salesTaxCode")
		delete(additionalProperties, "discountRate")
		delete(additionalProperties, "discountRatePercent")
		delete(additionalProperties, "account")
		delete(additionalProperties, "externalId")
		delete(additionalProperties, "customFields")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableQbdDiscountItem struct {
	value *QbdDiscountItem
	isSet bool
}

func (v NullableQbdDiscountItem) Get() *QbdDiscountItem {
	return v.value
}

func (v *NullableQbdDiscountItem) Set(val *QbdDiscountItem) {
	v.value = val
	v.isSet = true
}

func (v NullableQbdDiscountItem) IsSet() bool {
	return v.isSet
}

func (v *NullableQbdDiscountItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQbdDiscountItem(val *QbdDiscountItem) *NullableQbdDiscountItem {
	return &NullableQbdDiscountItem{value: val, isSet: true}
}

func (v NullableQbdDiscountItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQbdDiscountItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


