/*
Conductor API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conductor

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QbdCreditMemoCurrency type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QbdCreditMemoCurrency{}

// QbdCreditMemoCurrency The credit memo's currency. For built-in currencies, the name and code are standard international values. For user-defined currencies, all values are editable.
type QbdCreditMemoCurrency struct {
	// The unique identifier assigned by QuickBooks to this object. This ID is unique across all objects of the same type, but not across different QuickBooks object types.
	Id string `json:"id"`
	// The fully-qualified unique name for this object, formed by combining the names of its parent objects with its own `name`, separated by colons. Not case-sensitive.
	FullName string `json:"fullName"`
}

type _QbdCreditMemoCurrency QbdCreditMemoCurrency

// NewQbdCreditMemoCurrency instantiates a new QbdCreditMemoCurrency object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQbdCreditMemoCurrency(id string, fullName string) *QbdCreditMemoCurrency {
	this := QbdCreditMemoCurrency{}
	this.Id = id
	this.FullName = fullName
	return &this
}

// NewQbdCreditMemoCurrencyWithDefaults instantiates a new QbdCreditMemoCurrency object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQbdCreditMemoCurrencyWithDefaults() *QbdCreditMemoCurrency {
	this := QbdCreditMemoCurrency{}
	return &this
}

// GetId returns the Id field value
func (o *QbdCreditMemoCurrency) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *QbdCreditMemoCurrency) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *QbdCreditMemoCurrency) SetId(v string) {
	o.Id = v
}

// GetFullName returns the FullName field value
func (o *QbdCreditMemoCurrency) GetFullName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FullName
}

// GetFullNameOk returns a tuple with the FullName field value
// and a boolean to check if the value has been set.
func (o *QbdCreditMemoCurrency) GetFullNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FullName, true
}

// SetFullName sets field value
func (o *QbdCreditMemoCurrency) SetFullName(v string) {
	o.FullName = v
}

func (o QbdCreditMemoCurrency) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QbdCreditMemoCurrency) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["fullName"] = o.FullName
	return toSerialize, nil
}

func (o *QbdCreditMemoCurrency) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"fullName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQbdCreditMemoCurrency := _QbdCreditMemoCurrency{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQbdCreditMemoCurrency)

	if err != nil {
		return err
	}

	*o = QbdCreditMemoCurrency(varQbdCreditMemoCurrency)

	return err
}

type NullableQbdCreditMemoCurrency struct {
	value *QbdCreditMemoCurrency
	isSet bool
}

func (v NullableQbdCreditMemoCurrency) Get() *QbdCreditMemoCurrency {
	return v.value
}

func (v *NullableQbdCreditMemoCurrency) Set(val *QbdCreditMemoCurrency) {
	v.value = val
	v.isSet = true
}

func (v NullableQbdCreditMemoCurrency) IsSet() bool {
	return v.isSet
}

func (v *NullableQbdCreditMemoCurrency) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQbdCreditMemoCurrency(val *QbdCreditMemoCurrency) *NullableQbdCreditMemoCurrency {
	return &NullableQbdCreditMemoCurrency{value: val, isSet: true}
}

func (v NullableQbdCreditMemoCurrency) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQbdCreditMemoCurrency) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


