/*
Conductor API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conductor

import (
	"encoding/json"
	"fmt"
)

// checks if the QbdPurchaseOrderLineGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QbdPurchaseOrderLineGroup{}

// QbdPurchaseOrderLineGroup struct for QbdPurchaseOrderLineGroup
type QbdPurchaseOrderLineGroup struct {
	// The unique identifier assigned by QuickBooks to this purchase order line group. This ID is unique across all transaction line types.
	Id string `json:"id"`
	// The type of object. This value is always `\"qbd_purchase_order_line_group\"`.
	ObjectType string `json:"objectType"`
	ItemGroup QbdPurchaseOrderLineGroupItemGroup `json:"itemGroup"`
	// A description of this purchase order line group.
	Description string `json:"description"`
	// The quantity of the item group associated with this purchase order line group. This field cannot be cleared.  **NOTE**: Do not use this field if the associated item group is a discount item group.
	Quantity float32 `json:"quantity"`
	// The unit-of-measure used for the `quantity` in this purchase order line group. Must be a valid unit within the item's available units of measure.
	UnitOfMeasure string `json:"unitOfMeasure"`
	OverrideUnitOfMeasureSet QbdPurchaseOrderLineGroupOverrideUnitOfMeasureSet `json:"overrideUnitOfMeasureSet"`
	// Indicates whether the individual items in this purchase order line group and their separate amounts appear on printed forms.
	ShouldPrintItemsInGroup bool `json:"shouldPrintItemsInGroup"`
	// The total monetary amount of this purchase order line group, equivalent to the sum of the amounts in `lines`, represented as a decimal string.
	TotalAmount string `json:"totalAmount"`
	// The purchase order line group's line items, each representing a single product or service ordered.
	Lines []QbdPurchaseOrderLine `json:"lines"`
	// The custom fields for the purchase order line group object, added as user-defined data extensions, not included in the standard QuickBooks object.
	CustomFields []QbdCustomField `json:"customFields"`
	AdditionalProperties map[string]interface{}
}

type _QbdPurchaseOrderLineGroup QbdPurchaseOrderLineGroup

// NewQbdPurchaseOrderLineGroup instantiates a new QbdPurchaseOrderLineGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQbdPurchaseOrderLineGroup(id string, objectType string, itemGroup QbdPurchaseOrderLineGroupItemGroup, description string, quantity float32, unitOfMeasure string, overrideUnitOfMeasureSet QbdPurchaseOrderLineGroupOverrideUnitOfMeasureSet, shouldPrintItemsInGroup bool, totalAmount string, lines []QbdPurchaseOrderLine, customFields []QbdCustomField) *QbdPurchaseOrderLineGroup {
	this := QbdPurchaseOrderLineGroup{}
	this.Id = id
	this.ObjectType = objectType
	this.ItemGroup = itemGroup
	this.Description = description
	this.Quantity = quantity
	this.UnitOfMeasure = unitOfMeasure
	this.OverrideUnitOfMeasureSet = overrideUnitOfMeasureSet
	this.ShouldPrintItemsInGroup = shouldPrintItemsInGroup
	this.TotalAmount = totalAmount
	this.Lines = lines
	this.CustomFields = customFields
	return &this
}

// NewQbdPurchaseOrderLineGroupWithDefaults instantiates a new QbdPurchaseOrderLineGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQbdPurchaseOrderLineGroupWithDefaults() *QbdPurchaseOrderLineGroup {
	this := QbdPurchaseOrderLineGroup{}
	return &this
}

// GetId returns the Id field value
func (o *QbdPurchaseOrderLineGroup) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *QbdPurchaseOrderLineGroup) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *QbdPurchaseOrderLineGroup) SetId(v string) {
	o.Id = v
}

// GetObjectType returns the ObjectType field value
func (o *QbdPurchaseOrderLineGroup) GetObjectType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value
// and a boolean to check if the value has been set.
func (o *QbdPurchaseOrderLineGroup) GetObjectTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectType, true
}

// SetObjectType sets field value
func (o *QbdPurchaseOrderLineGroup) SetObjectType(v string) {
	o.ObjectType = v
}

// GetItemGroup returns the ItemGroup field value
func (o *QbdPurchaseOrderLineGroup) GetItemGroup() QbdPurchaseOrderLineGroupItemGroup {
	if o == nil {
		var ret QbdPurchaseOrderLineGroupItemGroup
		return ret
	}

	return o.ItemGroup
}

// GetItemGroupOk returns a tuple with the ItemGroup field value
// and a boolean to check if the value has been set.
func (o *QbdPurchaseOrderLineGroup) GetItemGroupOk() (*QbdPurchaseOrderLineGroupItemGroup, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ItemGroup, true
}

// SetItemGroup sets field value
func (o *QbdPurchaseOrderLineGroup) SetItemGroup(v QbdPurchaseOrderLineGroupItemGroup) {
	o.ItemGroup = v
}

// GetDescription returns the Description field value
func (o *QbdPurchaseOrderLineGroup) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *QbdPurchaseOrderLineGroup) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *QbdPurchaseOrderLineGroup) SetDescription(v string) {
	o.Description = v
}

// GetQuantity returns the Quantity field value
func (o *QbdPurchaseOrderLineGroup) GetQuantity() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *QbdPurchaseOrderLineGroup) GetQuantityOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *QbdPurchaseOrderLineGroup) SetQuantity(v float32) {
	o.Quantity = v
}

// GetUnitOfMeasure returns the UnitOfMeasure field value
func (o *QbdPurchaseOrderLineGroup) GetUnitOfMeasure() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UnitOfMeasure
}

// GetUnitOfMeasureOk returns a tuple with the UnitOfMeasure field value
// and a boolean to check if the value has been set.
func (o *QbdPurchaseOrderLineGroup) GetUnitOfMeasureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnitOfMeasure, true
}

// SetUnitOfMeasure sets field value
func (o *QbdPurchaseOrderLineGroup) SetUnitOfMeasure(v string) {
	o.UnitOfMeasure = v
}

// GetOverrideUnitOfMeasureSet returns the OverrideUnitOfMeasureSet field value
func (o *QbdPurchaseOrderLineGroup) GetOverrideUnitOfMeasureSet() QbdPurchaseOrderLineGroupOverrideUnitOfMeasureSet {
	if o == nil {
		var ret QbdPurchaseOrderLineGroupOverrideUnitOfMeasureSet
		return ret
	}

	return o.OverrideUnitOfMeasureSet
}

// GetOverrideUnitOfMeasureSetOk returns a tuple with the OverrideUnitOfMeasureSet field value
// and a boolean to check if the value has been set.
func (o *QbdPurchaseOrderLineGroup) GetOverrideUnitOfMeasureSetOk() (*QbdPurchaseOrderLineGroupOverrideUnitOfMeasureSet, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OverrideUnitOfMeasureSet, true
}

// SetOverrideUnitOfMeasureSet sets field value
func (o *QbdPurchaseOrderLineGroup) SetOverrideUnitOfMeasureSet(v QbdPurchaseOrderLineGroupOverrideUnitOfMeasureSet) {
	o.OverrideUnitOfMeasureSet = v
}

// GetShouldPrintItemsInGroup returns the ShouldPrintItemsInGroup field value
func (o *QbdPurchaseOrderLineGroup) GetShouldPrintItemsInGroup() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ShouldPrintItemsInGroup
}

// GetShouldPrintItemsInGroupOk returns a tuple with the ShouldPrintItemsInGroup field value
// and a boolean to check if the value has been set.
func (o *QbdPurchaseOrderLineGroup) GetShouldPrintItemsInGroupOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShouldPrintItemsInGroup, true
}

// SetShouldPrintItemsInGroup sets field value
func (o *QbdPurchaseOrderLineGroup) SetShouldPrintItemsInGroup(v bool) {
	o.ShouldPrintItemsInGroup = v
}

// GetTotalAmount returns the TotalAmount field value
func (o *QbdPurchaseOrderLineGroup) GetTotalAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TotalAmount
}

// GetTotalAmountOk returns a tuple with the TotalAmount field value
// and a boolean to check if the value has been set.
func (o *QbdPurchaseOrderLineGroup) GetTotalAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalAmount, true
}

// SetTotalAmount sets field value
func (o *QbdPurchaseOrderLineGroup) SetTotalAmount(v string) {
	o.TotalAmount = v
}

// GetLines returns the Lines field value
func (o *QbdPurchaseOrderLineGroup) GetLines() []QbdPurchaseOrderLine {
	if o == nil {
		var ret []QbdPurchaseOrderLine
		return ret
	}

	return o.Lines
}

// GetLinesOk returns a tuple with the Lines field value
// and a boolean to check if the value has been set.
func (o *QbdPurchaseOrderLineGroup) GetLinesOk() ([]QbdPurchaseOrderLine, bool) {
	if o == nil {
		return nil, false
	}
	return o.Lines, true
}

// SetLines sets field value
func (o *QbdPurchaseOrderLineGroup) SetLines(v []QbdPurchaseOrderLine) {
	o.Lines = v
}

// GetCustomFields returns the CustomFields field value
func (o *QbdPurchaseOrderLineGroup) GetCustomFields() []QbdCustomField {
	if o == nil {
		var ret []QbdCustomField
		return ret
	}

	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value
// and a boolean to check if the value has been set.
func (o *QbdPurchaseOrderLineGroup) GetCustomFieldsOk() ([]QbdCustomField, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomFields, true
}

// SetCustomFields sets field value
func (o *QbdPurchaseOrderLineGroup) SetCustomFields(v []QbdCustomField) {
	o.CustomFields = v
}

func (o QbdPurchaseOrderLineGroup) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QbdPurchaseOrderLineGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["objectType"] = o.ObjectType
	toSerialize["itemGroup"] = o.ItemGroup
	toSerialize["description"] = o.Description
	toSerialize["quantity"] = o.Quantity
	toSerialize["unitOfMeasure"] = o.UnitOfMeasure
	toSerialize["overrideUnitOfMeasureSet"] = o.OverrideUnitOfMeasureSet
	toSerialize["shouldPrintItemsInGroup"] = o.ShouldPrintItemsInGroup
	toSerialize["totalAmount"] = o.TotalAmount
	toSerialize["lines"] = o.Lines
	toSerialize["customFields"] = o.CustomFields

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *QbdPurchaseOrderLineGroup) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"objectType",
		"itemGroup",
		"description",
		"quantity",
		"unitOfMeasure",
		"overrideUnitOfMeasureSet",
		"shouldPrintItemsInGroup",
		"totalAmount",
		"lines",
		"customFields",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQbdPurchaseOrderLineGroup := _QbdPurchaseOrderLineGroup{}

	err = json.Unmarshal(data, &varQbdPurchaseOrderLineGroup)

	if err != nil {
		return err
	}

	*o = QbdPurchaseOrderLineGroup(varQbdPurchaseOrderLineGroup)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "objectType")
		delete(additionalProperties, "itemGroup")
		delete(additionalProperties, "description")
		delete(additionalProperties, "quantity")
		delete(additionalProperties, "unitOfMeasure")
		delete(additionalProperties, "overrideUnitOfMeasureSet")
		delete(additionalProperties, "shouldPrintItemsInGroup")
		delete(additionalProperties, "totalAmount")
		delete(additionalProperties, "lines")
		delete(additionalProperties, "customFields")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableQbdPurchaseOrderLineGroup struct {
	value *QbdPurchaseOrderLineGroup
	isSet bool
}

func (v NullableQbdPurchaseOrderLineGroup) Get() *QbdPurchaseOrderLineGroup {
	return v.value
}

func (v *NullableQbdPurchaseOrderLineGroup) Set(val *QbdPurchaseOrderLineGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableQbdPurchaseOrderLineGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableQbdPurchaseOrderLineGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQbdPurchaseOrderLineGroup(val *QbdPurchaseOrderLineGroup) *NullableQbdPurchaseOrderLineGroup {
	return &NullableQbdPurchaseOrderLineGroup{value: val, isSet: true}
}

func (v NullableQbdPurchaseOrderLineGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQbdPurchaseOrderLineGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


