/*
Conductor API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conductor

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QbdSalesReceiptCustomer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QbdSalesReceiptCustomer{}

// QbdSalesReceiptCustomer The customer or customer-job to which the payment for this sales receipt is credited.
type QbdSalesReceiptCustomer struct {
	// The unique identifier assigned by QuickBooks to this object. This ID is unique across all objects of the same type, but not across different QuickBooks object types.
	Id string `json:"id"`
	// The fully-qualified unique name for this object, formed by combining the names of its parent objects with its own `name`, separated by colons. Not case-sensitive.
	FullName string `json:"fullName"`
}

type _QbdSalesReceiptCustomer QbdSalesReceiptCustomer

// NewQbdSalesReceiptCustomer instantiates a new QbdSalesReceiptCustomer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQbdSalesReceiptCustomer(id string, fullName string) *QbdSalesReceiptCustomer {
	this := QbdSalesReceiptCustomer{}
	this.Id = id
	this.FullName = fullName
	return &this
}

// NewQbdSalesReceiptCustomerWithDefaults instantiates a new QbdSalesReceiptCustomer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQbdSalesReceiptCustomerWithDefaults() *QbdSalesReceiptCustomer {
	this := QbdSalesReceiptCustomer{}
	return &this
}

// GetId returns the Id field value
func (o *QbdSalesReceiptCustomer) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *QbdSalesReceiptCustomer) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *QbdSalesReceiptCustomer) SetId(v string) {
	o.Id = v
}

// GetFullName returns the FullName field value
func (o *QbdSalesReceiptCustomer) GetFullName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FullName
}

// GetFullNameOk returns a tuple with the FullName field value
// and a boolean to check if the value has been set.
func (o *QbdSalesReceiptCustomer) GetFullNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FullName, true
}

// SetFullName sets field value
func (o *QbdSalesReceiptCustomer) SetFullName(v string) {
	o.FullName = v
}

func (o QbdSalesReceiptCustomer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QbdSalesReceiptCustomer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["fullName"] = o.FullName
	return toSerialize, nil
}

func (o *QbdSalesReceiptCustomer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"fullName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQbdSalesReceiptCustomer := _QbdSalesReceiptCustomer{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQbdSalesReceiptCustomer)

	if err != nil {
		return err
	}

	*o = QbdSalesReceiptCustomer(varQbdSalesReceiptCustomer)

	return err
}

type NullableQbdSalesReceiptCustomer struct {
	value *QbdSalesReceiptCustomer
	isSet bool
}

func (v NullableQbdSalesReceiptCustomer) Get() *QbdSalesReceiptCustomer {
	return v.value
}

func (v *NullableQbdSalesReceiptCustomer) Set(val *QbdSalesReceiptCustomer) {
	v.value = val
	v.isSet = true
}

func (v NullableQbdSalesReceiptCustomer) IsSet() bool {
	return v.isSet
}

func (v *NullableQbdSalesReceiptCustomer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQbdSalesReceiptCustomer(val *QbdSalesReceiptCustomer) *NullableQbdSalesReceiptCustomer {
	return &NullableQbdSalesReceiptCustomer{value: val, isSet: true}
}

func (v NullableQbdSalesReceiptCustomer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQbdSalesReceiptCustomer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


