/*
Conductor API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conductor

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TheFinanceChargePreferencesObjectFinanceChargeAccount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TheFinanceChargePreferencesObjectFinanceChargeAccount{}

// TheFinanceChargePreferencesObjectFinanceChargeAccount The account used to track finance charges that customers pay for this company file. This is usually an income account.
type TheFinanceChargePreferencesObjectFinanceChargeAccount struct {
	// The unique identifier assigned by QuickBooks to this object. This ID is unique across all objects of the same type, but not across different QuickBooks object types.
	Id string `json:"id"`
	// The fully-qualified unique name for this object, formed by combining the names of its parent objects with its own `name`, separated by colons. Not case-sensitive.
	FullName string `json:"fullName"`
}

type _TheFinanceChargePreferencesObjectFinanceChargeAccount TheFinanceChargePreferencesObjectFinanceChargeAccount

// NewTheFinanceChargePreferencesObjectFinanceChargeAccount instantiates a new TheFinanceChargePreferencesObjectFinanceChargeAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTheFinanceChargePreferencesObjectFinanceChargeAccount(id string, fullName string) *TheFinanceChargePreferencesObjectFinanceChargeAccount {
	this := TheFinanceChargePreferencesObjectFinanceChargeAccount{}
	this.Id = id
	this.FullName = fullName
	return &this
}

// NewTheFinanceChargePreferencesObjectFinanceChargeAccountWithDefaults instantiates a new TheFinanceChargePreferencesObjectFinanceChargeAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTheFinanceChargePreferencesObjectFinanceChargeAccountWithDefaults() *TheFinanceChargePreferencesObjectFinanceChargeAccount {
	this := TheFinanceChargePreferencesObjectFinanceChargeAccount{}
	return &this
}

// GetId returns the Id field value
func (o *TheFinanceChargePreferencesObjectFinanceChargeAccount) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TheFinanceChargePreferencesObjectFinanceChargeAccount) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TheFinanceChargePreferencesObjectFinanceChargeAccount) SetId(v string) {
	o.Id = v
}

// GetFullName returns the FullName field value
func (o *TheFinanceChargePreferencesObjectFinanceChargeAccount) GetFullName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FullName
}

// GetFullNameOk returns a tuple with the FullName field value
// and a boolean to check if the value has been set.
func (o *TheFinanceChargePreferencesObjectFinanceChargeAccount) GetFullNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FullName, true
}

// SetFullName sets field value
func (o *TheFinanceChargePreferencesObjectFinanceChargeAccount) SetFullName(v string) {
	o.FullName = v
}

func (o TheFinanceChargePreferencesObjectFinanceChargeAccount) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TheFinanceChargePreferencesObjectFinanceChargeAccount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["fullName"] = o.FullName
	return toSerialize, nil
}

func (o *TheFinanceChargePreferencesObjectFinanceChargeAccount) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"fullName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTheFinanceChargePreferencesObjectFinanceChargeAccount := _TheFinanceChargePreferencesObjectFinanceChargeAccount{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTheFinanceChargePreferencesObjectFinanceChargeAccount)

	if err != nil {
		return err
	}

	*o = TheFinanceChargePreferencesObjectFinanceChargeAccount(varTheFinanceChargePreferencesObjectFinanceChargeAccount)

	return err
}

type NullableTheFinanceChargePreferencesObjectFinanceChargeAccount struct {
	value *TheFinanceChargePreferencesObjectFinanceChargeAccount
	isSet bool
}

func (v NullableTheFinanceChargePreferencesObjectFinanceChargeAccount) Get() *TheFinanceChargePreferencesObjectFinanceChargeAccount {
	return v.value
}

func (v *NullableTheFinanceChargePreferencesObjectFinanceChargeAccount) Set(val *TheFinanceChargePreferencesObjectFinanceChargeAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableTheFinanceChargePreferencesObjectFinanceChargeAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableTheFinanceChargePreferencesObjectFinanceChargeAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTheFinanceChargePreferencesObjectFinanceChargeAccount(val *TheFinanceChargePreferencesObjectFinanceChargeAccount) *NullableTheFinanceChargePreferencesObjectFinanceChargeAccount {
	return &NullableTheFinanceChargePreferencesObjectFinanceChargeAccount{value: val, isSet: true}
}

func (v NullableTheFinanceChargePreferencesObjectFinanceChargeAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTheFinanceChargePreferencesObjectFinanceChargeAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


