/*
Conductor API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conductor

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// QbdPreferencesMultiCurrency - The multi-currency preferences for this company file.
type QbdPreferencesMultiCurrency struct {
	QbdMultiCurrencyPreferences *QbdMultiCurrencyPreferences
}

// QbdMultiCurrencyPreferencesAsQbdPreferencesMultiCurrency is a convenience function that returns QbdMultiCurrencyPreferences wrapped in QbdPreferencesMultiCurrency
func QbdMultiCurrencyPreferencesAsQbdPreferencesMultiCurrency(v *QbdMultiCurrencyPreferences) QbdPreferencesMultiCurrency {
	return QbdPreferencesMultiCurrency{
		QbdMultiCurrencyPreferences: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *QbdPreferencesMultiCurrency) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into QbdMultiCurrencyPreferences
	err = newStrictDecoder(data).Decode(&dst.QbdMultiCurrencyPreferences)
	if err == nil {
		jsonQbdMultiCurrencyPreferences, _ := json.Marshal(dst.QbdMultiCurrencyPreferences)
		if string(jsonQbdMultiCurrencyPreferences) == "{}" { // empty struct
			dst.QbdMultiCurrencyPreferences = nil
		} else {
			if err = validator.Validate(dst.QbdMultiCurrencyPreferences); err != nil {
				dst.QbdMultiCurrencyPreferences = nil
			} else {
				match++
			}
		}
	} else {
		dst.QbdMultiCurrencyPreferences = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.QbdMultiCurrencyPreferences = nil

		return fmt.Errorf("data matches more than one schema in oneOf(QbdPreferencesMultiCurrency)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(QbdPreferencesMultiCurrency)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src QbdPreferencesMultiCurrency) MarshalJSON() ([]byte, error) {
	if src.QbdMultiCurrencyPreferences != nil {
		return json.Marshal(&src.QbdMultiCurrencyPreferences)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *QbdPreferencesMultiCurrency) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.QbdMultiCurrencyPreferences != nil {
		return obj.QbdMultiCurrencyPreferences
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj QbdPreferencesMultiCurrency) GetActualInstanceValue() (interface{}) {
	if obj.QbdMultiCurrencyPreferences != nil {
		return *obj.QbdMultiCurrencyPreferences
	}

	// all schemas are nil
	return nil
}

type NullableQbdPreferencesMultiCurrency struct {
	value *QbdPreferencesMultiCurrency
	isSet bool
}

func (v NullableQbdPreferencesMultiCurrency) Get() *QbdPreferencesMultiCurrency {
	return v.value
}

func (v *NullableQbdPreferencesMultiCurrency) Set(val *QbdPreferencesMultiCurrency) {
	v.value = val
	v.isSet = true
}

func (v NullableQbdPreferencesMultiCurrency) IsSet() bool {
	return v.isSet
}

func (v *NullableQbdPreferencesMultiCurrency) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQbdPreferencesMultiCurrency(val *QbdPreferencesMultiCurrency) *NullableQbdPreferencesMultiCurrency {
	return &NullableQbdPreferencesMultiCurrency{value: val, isSet: true}
}

func (v NullableQbdPreferencesMultiCurrency) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQbdPreferencesMultiCurrency) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


