/*
Conductor API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conductor

import (
	"encoding/json"
	"fmt"
)

// checks if the QbdPurchasesAndVendorsPreferences type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QbdPurchasesAndVendorsPreferences{}

// QbdPurchasesAndVendorsPreferences struct for QbdPurchasesAndVendorsPreferences
type QbdPurchasesAndVendorsPreferences struct {
	// Indicates whether this company file has inventory-related features enabled.
	IsUsingInventory bool `json:"isUsingInventory"`
	// The default number of days after receipt when bills are due for this company file.
	DaysBillsAreDue float32 `json:"daysBillsAreDue"`
	// Indicates whether this company file is configured to automatically apply available vendor discounts or credits when paying bills.
	IsAutomaticallyUsingDiscounts bool `json:"isAutomaticallyUsingDiscounts"`
	DefaultDiscountAccount QbdPurchasesAndVendorsPreferencesDefaultDiscountAccount `json:"defaultDiscountAccount"`
	AdditionalProperties map[string]interface{}
}

type _QbdPurchasesAndVendorsPreferences QbdPurchasesAndVendorsPreferences

// NewQbdPurchasesAndVendorsPreferences instantiates a new QbdPurchasesAndVendorsPreferences object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQbdPurchasesAndVendorsPreferences(isUsingInventory bool, daysBillsAreDue float32, isAutomaticallyUsingDiscounts bool, defaultDiscountAccount QbdPurchasesAndVendorsPreferencesDefaultDiscountAccount) *QbdPurchasesAndVendorsPreferences {
	this := QbdPurchasesAndVendorsPreferences{}
	this.IsUsingInventory = isUsingInventory
	this.DaysBillsAreDue = daysBillsAreDue
	this.IsAutomaticallyUsingDiscounts = isAutomaticallyUsingDiscounts
	this.DefaultDiscountAccount = defaultDiscountAccount
	return &this
}

// NewQbdPurchasesAndVendorsPreferencesWithDefaults instantiates a new QbdPurchasesAndVendorsPreferences object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQbdPurchasesAndVendorsPreferencesWithDefaults() *QbdPurchasesAndVendorsPreferences {
	this := QbdPurchasesAndVendorsPreferences{}
	return &this
}

// GetIsUsingInventory returns the IsUsingInventory field value
func (o *QbdPurchasesAndVendorsPreferences) GetIsUsingInventory() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsUsingInventory
}

// GetIsUsingInventoryOk returns a tuple with the IsUsingInventory field value
// and a boolean to check if the value has been set.
func (o *QbdPurchasesAndVendorsPreferences) GetIsUsingInventoryOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsUsingInventory, true
}

// SetIsUsingInventory sets field value
func (o *QbdPurchasesAndVendorsPreferences) SetIsUsingInventory(v bool) {
	o.IsUsingInventory = v
}

// GetDaysBillsAreDue returns the DaysBillsAreDue field value
func (o *QbdPurchasesAndVendorsPreferences) GetDaysBillsAreDue() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.DaysBillsAreDue
}

// GetDaysBillsAreDueOk returns a tuple with the DaysBillsAreDue field value
// and a boolean to check if the value has been set.
func (o *QbdPurchasesAndVendorsPreferences) GetDaysBillsAreDueOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DaysBillsAreDue, true
}

// SetDaysBillsAreDue sets field value
func (o *QbdPurchasesAndVendorsPreferences) SetDaysBillsAreDue(v float32) {
	o.DaysBillsAreDue = v
}

// GetIsAutomaticallyUsingDiscounts returns the IsAutomaticallyUsingDiscounts field value
func (o *QbdPurchasesAndVendorsPreferences) GetIsAutomaticallyUsingDiscounts() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsAutomaticallyUsingDiscounts
}

// GetIsAutomaticallyUsingDiscountsOk returns a tuple with the IsAutomaticallyUsingDiscounts field value
// and a boolean to check if the value has been set.
func (o *QbdPurchasesAndVendorsPreferences) GetIsAutomaticallyUsingDiscountsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsAutomaticallyUsingDiscounts, true
}

// SetIsAutomaticallyUsingDiscounts sets field value
func (o *QbdPurchasesAndVendorsPreferences) SetIsAutomaticallyUsingDiscounts(v bool) {
	o.IsAutomaticallyUsingDiscounts = v
}

// GetDefaultDiscountAccount returns the DefaultDiscountAccount field value
func (o *QbdPurchasesAndVendorsPreferences) GetDefaultDiscountAccount() QbdPurchasesAndVendorsPreferencesDefaultDiscountAccount {
	if o == nil {
		var ret QbdPurchasesAndVendorsPreferencesDefaultDiscountAccount
		return ret
	}

	return o.DefaultDiscountAccount
}

// GetDefaultDiscountAccountOk returns a tuple with the DefaultDiscountAccount field value
// and a boolean to check if the value has been set.
func (o *QbdPurchasesAndVendorsPreferences) GetDefaultDiscountAccountOk() (*QbdPurchasesAndVendorsPreferencesDefaultDiscountAccount, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefaultDiscountAccount, true
}

// SetDefaultDiscountAccount sets field value
func (o *QbdPurchasesAndVendorsPreferences) SetDefaultDiscountAccount(v QbdPurchasesAndVendorsPreferencesDefaultDiscountAccount) {
	o.DefaultDiscountAccount = v
}

func (o QbdPurchasesAndVendorsPreferences) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QbdPurchasesAndVendorsPreferences) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["isUsingInventory"] = o.IsUsingInventory
	toSerialize["daysBillsAreDue"] = o.DaysBillsAreDue
	toSerialize["isAutomaticallyUsingDiscounts"] = o.IsAutomaticallyUsingDiscounts
	toSerialize["defaultDiscountAccount"] = o.DefaultDiscountAccount

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *QbdPurchasesAndVendorsPreferences) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"isUsingInventory",
		"daysBillsAreDue",
		"isAutomaticallyUsingDiscounts",
		"defaultDiscountAccount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQbdPurchasesAndVendorsPreferences := _QbdPurchasesAndVendorsPreferences{}

	err = json.Unmarshal(data, &varQbdPurchasesAndVendorsPreferences)

	if err != nil {
		return err
	}

	*o = QbdPurchasesAndVendorsPreferences(varQbdPurchasesAndVendorsPreferences)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "isUsingInventory")
		delete(additionalProperties, "daysBillsAreDue")
		delete(additionalProperties, "isAutomaticallyUsingDiscounts")
		delete(additionalProperties, "defaultDiscountAccount")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableQbdPurchasesAndVendorsPreferences struct {
	value *QbdPurchasesAndVendorsPreferences
	isSet bool
}

func (v NullableQbdPurchasesAndVendorsPreferences) Get() *QbdPurchasesAndVendorsPreferences {
	return v.value
}

func (v *NullableQbdPurchasesAndVendorsPreferences) Set(val *QbdPurchasesAndVendorsPreferences) {
	v.value = val
	v.isSet = true
}

func (v NullableQbdPurchasesAndVendorsPreferences) IsSet() bool {
	return v.isSet
}

func (v *NullableQbdPurchasesAndVendorsPreferences) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQbdPurchasesAndVendorsPreferences(val *QbdPurchasesAndVendorsPreferences) *NullableQbdPurchasesAndVendorsPreferences {
	return &NullableQbdPurchasesAndVendorsPreferences{value: val, isSet: true}
}

func (v NullableQbdPurchasesAndVendorsPreferences) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQbdPurchasesAndVendorsPreferences) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


